sulu_admin:
    resources:
        events:
            routes:
                list: app.get_events
                detail: app.get_event
    field_type_options:
        selection:
            event_selection:
                default_type: list_overlay
                resource_key: events
                types:
                    list_overlay:
                        adapter: table
                        list_key: events
                        display_properties:
                            - title
                        icon: fa-calendar
                        label: 'app.events'
                        overlay_title: 'app.events'
