# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    default_locale: en

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $listBuilderFactory: '@sulu_core.doctrine_list_builder_factory'

    _instanceof:
        Sulu\Bundle\AdminBundle\Admin\Admin:
            tags: ['sulu.admin', {name: 'sulu.context', context: 'admin'}]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,DataFixtures,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Content\EventSelectionContentType:
        tags: [{name: 'sulu.content.type', alias: 'event_selection'}]

    App\Content\EventDataProvider:
        tags: [{name: 'sulu.smart_content.data_provider', alias: 'event'}]
        bind:
            $repository: '@App\Repository\EventRepository'

    # following service definitions will be removed in the website context of sulu
    App\Admin\:
        resource: '../src/Admin'
        tags: [{name: 'sulu.context', context: 'admin'}]

    App\Controller\Admin\:
        resource: '../src/Controller/Admin'
        tags: [{name: 'sulu.context', context: 'admin'}]
